# https://travis-ci.org/vmous/yocto-toolbox
sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  # PyPy versions
  - "pypy"  # PyPy2 2.5.0
  - "pypy3" # Pypy3 2.4.0
  - "pypy-5.3.1"
# command to install dependencies
os:
  - linux
install:
  - pip install -r requirements.txt
script:  "python setup.py test"
notifications:
  email: false
